### ISSUE TITLE
Connection Error with FortiOS 7.4.5

### ISSUE THREAD

**Issue by PhilooLinux** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#359]
Hello,

I am using several playbooks against many Fortigate (50+) and recently I see all the ones running with FortiOS 7.4.5 failing with the error message:
`The error was: ansible.module_utils.connection.ConnectionError: Expecting value: line 1 column 1 (char 0)`

I am using:
```
ansible [core 2.17.6]
  config file = /home/ansible/setup/firewall/ansible.cfg
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/ansible/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.2 (main, Sep 14 2024, 03:00:30) [GCC 12.2.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

and
```
ansible-galaxy collection list | grep fortios
fortinet.fortios                         2.3.8
fortinet.fortios                         2.3.8
```

Looking at the [FortiOS Release Notes for 7.4.5](https://docs.fortinet.com/document/fortigate/7.4.5/fortios-release-notes/760203/introduction-and-supported-models), I fail to see any known issue or change regarding Rest API.

Could you help me solving this problem?
Thanks.

**Comment by MaxxLiu22** [comment]
Hi @PhilooLinux ,

Thank you for raising this issue. I tested this on my FOS 7.4.5, and everything worked as expected. However, I encountered the same issue when I provided an incorrect token in the following configuration: ``ansible_httpapi_session_key={"access_token":"rkknN4QQ...."}`` in host file. Could you please double-check if your token is valid? If that is not the reason, could you provide more details, such as your host file and playbook configuration, the authentication method you are using (token or username/password), and any other relevant information?

Thanks,
Maxx

**Comment by MaxxLiu22** [comment]
Hi @PhilooLinux ，

Thank you for sharing this information. The playbook runs successfully on my end, so if the issue only occurs with FOS 7.4.5, it may not be related to Ansible. I understand that starting with FOS 7.4.5, a feature was introduced to restrict providing authentication information in the URL. Ansible FOS 2.3.8 should handle this change. However, to ensure minimal impact on current customers, the argument ``rest-api-key-url-query`` was added under system global to control this behavior, and it is disabled by default.

```
FGT-VM-103 # config system global  
FGT-VM-103 (global) # set rest-api-key-url-query disable  
```
For testing, I enabled the argument, but Ansible FOS still functioned as expected. Could you kindly provide an example of your host file? Additionally, I’d like to understand how the username and password are provided. Are there any special characters in them that could potentially contribute to the issue? This is one potential cause I can think of.

If the issue persists, enabling both Ansible’s debug function and FOS’s debug function might offer more insights to help us identify the root cause.

```
ansible-playbook -i hosts issue359.yaml -vvv  
```
FGT-VM-103 # diagnose debug application httpsd -1  
Debug messages will be on for 20 minutes.  
FGT-VM-103 # diagnose debug enable  
```
Thank you, and I look forward to your response.
Maxx

**Comment by PhilooLinux** [comment]
Hi @MaxxLiu22 ,

This parameter, as you mentioned, was indeed already disabled. I tried it also with "enable" but the behaviour does not change.

I have reproduced the issue in debug mode on both sides ( with _rest-api-key-url-query disable_) :

Using this inventory in YML format:
```
---
fw-01:
     hosts:
        fw-01.???.com:
            ansible_host: fw-01.???.com
            fqdn: yes
            ansible_httpapi_port: 11115
            ansible_user: "Ansible"
            ansible_password: !vault |
              $ANSIBLE_VAULT;1.1;AES256
              33313437666237656562663462383263313732343739393766333666373964303339323233656563
              3135383836316438653934383737636230623066313561300a376436343338616264633535393766
              34343066306630373565396532623863323932356235383961303636376537373761346461393563
              3630643461656330340a346133393762663163633964383632313964313133396266613662376235
              3064

fortigate:
    children:
        fw-01:
    vars:
        ansible_network_os: fortinet.fortios.fortios
...
```

This is part of the result from Ansible:
```
<fw-01.???.com> EXEC /bin/sh -c 'rm -f -r /home/ansible/.ansible/tmp/ansible-local-85173s0lgj8uc/ansible-tmp-1732796383.7904794-85290-234895726526624/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/ansible/.ansible/tmp/ansible-local-85173s0lgj8uc/ansible-tmp-1732796383.7904794-85290-234895726526624/AnsiballZ_fortios_monitor_fact.py", line 107, in <module>
    _ansiballz_main()
  File "/home/ansible/.ansible/tmp/ansible-local-85173s0lgj8uc/ansible-tmp-1732796383.7904794-85290-234895726526624/AnsiballZ_fortios_monitor_fact.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/ansible/.ansible/tmp/ansible-local-85173s0lgj8uc/ansible-tmp-1732796383.7904794-85290-234895726526624/AnsiballZ_fortios_monitor_fact.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.fortinet.fortios.plugins.modules.fortios_monitor_fact', init_globals=dict(_module_fqn='ansible_collections.fortinet.fortios.plugins.modules.fortios_monitor_fact', _modlib_path=modlib_path),
  File "<frozen runpy>", line 226, in run_module
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/ansible_fortinet.fortios.fortios_monitor_fact_payload_mvj77ys_/ansible_fortinet.fortios.fortios_monitor_fact_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_monitor_fact.py", line 3306, in <module>
  File "/tmp/ansible_fortinet.fortios.fortios_monitor_fact_payload_mvj77ys_/ansible_fortinet.fortios.fortios_monitor_fact_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_monitor_fact.py", line 3270, in main
  File "/tmp/ansible_fortinet.fortios.fortios_monitor_fact_payload_mvj77ys_/ansible_fortinet.fortios.fortios_monitor_fact_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_monitor_fact.py", line 2530, in fortios_monitor_fact
  File "/tmp/ansible_fortinet.fortios.fortios_monitor_fact_payload_mvj77ys_/ansible_fortinet.fortios.fortios_monitor_fact_payload.zip/ansible_collections/fortinet/fortios/plugins/module_utils/fortios/fortios.py", line 580, in monitor_get
  File "/tmp/ansible_fortinet.fortios.fortios_monitor_fact_payload_mvj77ys_/ansible_fortinet.fortios.fortios_monitor_fact_payload.zip/ansible/module_utils/connection.py", line 199, in __rpc__
ansible.module_utils.connection.ConnectionError: Expecting value: line 1 column 1 (char 0)
fatal: [fw-01]: FAILED! => changed=false
  module_stderr: |-
    Traceback (most recent call last):
      File "/home/ansible/.ansible/tmp/ansible-local-85173s0lgj8uc/ansible-tmp-1732796383.7904794-85290-234895726526624/AnsiballZ_fortios_monitor_fact.py", line 107, in <module>
        _ansiballz_main()
      File "/home/ansible/.ansible/tmp/ansible-local-85173s0lgj8uc/ansible-tmp-1732796383.7904794-85290-234895726526624/AnsiballZ_fortios_monitor_fact.py", line 99, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/ansible/.ansible/tmp/ansible-local-85173s0lgj8uc/ansible-tmp-1732796383.7904794-85290-234895726526624/AnsiballZ_fortios_monitor_fact.py", line 47, in invoke_module
        runpy.run_module(mod_name='ansible_collections.fortinet.fortios.plugins.modules.fortios_monitor_fact', init_globals=dict(_module_fqn='ansible_collections.fortinet.fortios.plugins.modules.fortios_monitor_fact', _modlib_path=modlib_path),
      File "<frozen runpy>", line 226, in run_module
      File "<frozen runpy>", line 98, in _run_module_code
      File "<frozen runpy>", line 88, in _run_code
      File "/tmp/ansible_fortinet.fortios.fortios_monitor_fact_payload_mvj77ys_/ansible_fortinet.fortios.fortios_monitor_fact_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_monitor_fact.py", line 3306, in <module>
      File "/tmp/ansible_fortinet.fortios.fortios_monitor_fact_payload_mvj77ys_/ansible_fortinet.fortios.fortios_monitor_fact_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_monitor_fact.py", line 3270, in main
      File "/tmp/ansible_fortinet.fortios.fortios_monitor_fact_payload_mvj77ys_/ansible_fortinet.fortios.fortios_monitor_fact_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_monitor_fact.py", line 2530, in fortios_monitor_fact
      File "/tmp/ansible_fortinet.fortios.fortios_monitor_fact_payload_mvj77ys_/ansible_fortinet.fortios.fortios_monitor_fact_payload.zip/ansible_collections/fortinet/fortios/plugins/module_utils/fortios/fortios.py", line 580, in monitor_get
      File "/tmp/ansible_fortinet.fortios.fortios_monitor_fact_payload_mvj77ys_/ansible_fortinet.fortios.fortios_monitor_fact_payload.zip/ansible/module_utils/connection.py", line 199, in __rpc__
    ansible.module_utils.connection.ConnectionError: Expecting value: line 1 column 1 (char 0)
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```

And from the Fortigate side (I was logged as "admin"):
```
FW-01 # diagnose debug enable

FW-01 # [httpsd 27304 - 1732796382     info] fweb_debug_init[531] -- New GET request for "/api/v2/monitor/system/usb-log" from "???.???.160.1:36586"
[httpsd 27304 - 1732796382     info] fweb_debug_init[533] -- User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0"
[httpsd 27304 - 1732796382     info] fweb_debug_init[535] -- Handler "api_monitor_v2-handler" assigned to request
[httpsd 27304 - 1732796382  warning] _extract_key_param[97] -- REST API key in URL parameters is disabled.
[httpsd 27304 - 1732796382  warning] _extract_key_param[97] -- REST API key in URL parameters is disabled.
[httpsd 27304 - 1732796382     info] api_store_parameter[334] -- add API parameter 'vdom' (type=string)
[httpsd 27304 - 1732796382     info] endpoint_process_req_vdom[1084] -- new API request (action='select',path='system',name='usb-log',vdom='root',user='admin')
[httpsd 27304 - 1732796382     info] endpoint_process_req_vdom[1090] -- completed API request (rss_pre=19636, rss_post=19636, rss_delta=0)
[httpsd 27304 - 1732796382     info] fweb_debug_final[355] -- Completed GET request for "/api/v2/monitor/system/usb-log" (HTTP 200)
[httpsd 27304 - 1732796384     info] fweb_debug_init[531] -- New POST request for "/api/v2/authentication" from "???.???.160.1:27600"
[httpsd 27304 - 1732796384     info] fweb_debug_init[533] -- User-Agent: "Python-urllib/3.11"
[httpsd 27304 - 1732796384     info] fweb_debug_init[535] -- Handler "api_authentication-handler" assigned to request
[httpsd 27304 - 1732796384     info] api_store_parameter[334] -- add API parameter 'username' (type=string)
[httpsd 27304 - 1732796384     info] api_store_parameter[334] -- add API parameter 'secretkey' (type=string)
[httpsd 27304 - 1732796384     info] api_store_parameter[334] -- add API parameter 'ack_post_disclaimer' (type=boolean)
[httpsd 27304 - 1732796384     info] api_store_parameter[334] -- add API parameter 'ack_pre_disclaimer' (type=boolean)
[httpsd 27304 - 1732796384     info] api_store_parameter[334] -- add API parameter 'request_key' (type=boolean)
[httpsd 27304 - 1732796384     info] api_login_login_attempt[615] -- entering vdom for login_attempt (vdom='root')
[httpsd 27304 - 1732796384     info] api_login_login_attempt[697] -- login_attempt (method=6, vdom='root', name='Ansible',admin_name='Ansible', auth_svr=''), result code: 0
[httpsd 27304 - 1732796384     info] api_login_set_admin_session[205] -- VDOM updated to 'root'
[httpsd 27304 - 1732796384     info] api_login_create_admin_session[156] -- Setting login context from GUI(???.???.160.1)
[httpsd 27304 - 1732796384     info] fweb_debug_final[355] -- Completed POST request for "/api/v2/authentication" (HTTP 200)
[httpsd 27304 - 1732796384     info] fweb_debug_init[531] -- New GET request for "/api/v2/monitor/system/status" from "???.???.160.1:9430"
[httpsd 27304 - 1732796384     info] fweb_debug_init[533] -- User-Agent: "Python-urllib/3.11"
[httpsd 27304 - 1732796384     info] fweb_debug_init[535] -- Handler "api_monitor_v2-handler" assigned to request
[httpsd 27304 - 1732796384  warning] _extract_key_param[97] -- REST API key in URL parameters is disabled.
[httpsd 27304 - 1732796384  warning] _extract_key_param[97] -- REST API key in URL parameters is disabled.
[httpsd 27304 - 1732796384     info] fweb_debug_final[355] -- Completed GET request for "/api/v2/monitor/system/status" (HTTP 401 Unauthorized)
[httpsd 27304 - 1732796384     info] fweb_debug_init[531] -- New DELETE request for "/api/v2/authentication" from "???.???.160.1:26980"
[httpsd 27304 - 1732796384     info] fweb_debug_init[533] -- User-Agent: "Python-urllib/3.11"
[httpsd 27304 - 1732796384     info] fweb_debug_init[535] -- Handler "api_authentication-handler" assigned to request
[httpsd 27304 - 1732796384     info] fweb_debug_final[355] -- Completed DELETE request for "/api/v2/authentication" (HTTP 200)
```

I have obfuscated some sensitive information with "?"

The vault encrypted password is alphanumeric only, so this shouldn't be a problem either.
I guess, I can compare with a working Firewall. I will try later on.

Thank you, Maxx

**Comment by MaxxLiu22** [comment]
Hi @PhilooLinux,

Your script is running well on my end, so I suspect the issue might be related to a setting in your FOS 7.4.5. It’s possible that some configurations changed during the version switch. Since my VM is a newly set-up FOS 7.4.5 device with no additional configurations, would you be willing to back up and share your VM configuration for further investigation? Please feel free to open the config file in a text editor and remove any sensitive information as needed.
```
root@liang:~/ansible/fgt/github#359# ansible-playbook -i inventory.yml github359.yaml 
[WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details

PLAY [fortigate] ********************************************************************************************************************************************************************************************************************

TASK [Gather Fortigate license status] **********************************************************************************************************************************************************************************************
ok: [fw-01.test.com]

TASK [Print license status] *********************************************************************************************************************************************************************************************************
ok: [fw-01.test.com] => {
    "data_struct.meta[1]": {
        "build": 2702,
        "http_method": "GET",
        "name": "status",
        "path": "system",
        "results": {
            "hostname": "FGT-VM-103",
            "log_disk_status": "available",
            "model": "FGVMK6",
            "model_name": "FortiGate",
            "model_number": "VM64-KVM"
        },
        "serial": "FGVMULTM24003288",
        "status": "success",
        "vdom": "root",
        "version": "v7.4.5"
    }
}

PLAY RECAP **************************************************************************************************************************************************************************************************************************
fw-01.test.com             : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

Thanks,
Maxx

**Comment by PhilooLinux** [comment]
Hi @MaxxLiu22,

You have already mentioned the fix (and reason for the issue) all along. Just that it should be enabled instead of disabled (which is the default). 
I manged to get a new Fortigate 60F which wasn't yet updated and worked fine. I upgraded the firmware to 7.4.5 and it showed the same behaviour. Enabling or allowing the key to be in the URL made it work again.

This worked for me not only on my test device but also on a production one:

```
config system global
	set rest-api-key-url-query enable
end
```
Could you please check on your side again because you mentioned not seeing a difference?

I think Ansible FOS 2.3.8 does not handle this change.

Thanks,
Philoo

**Comment by robindbe** [comment]
For us the error we keep getting on the Fortigate side is "login failed from https(192.168.1.1) because of incorrect login vdom". The firewalls is a model that does not have VDOMs so we just use root. Setting the 'rest-api-key-url-query' to enable changes nothing.

Code is super basic:
```
    - name: Fetch simple setting to test API access
      fortinet.fortios.fortios_configuration_fact:
        vdom: "root"
        access_token: "{{ access_token }}"
        selector: system_global
      register: reg_forti_system
```

And under group_vars:
```
ansible_connection: httpapi
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false
ansible_httpapi_port: 443
ansible_network_os: fortinet.fortios.fortios
```

**Comment by MaxxLiu22** [comment]
Hi @robindbe @PhilooLinux ,

I tested @robindbe's scripts on my FGT 60F (version 7.4.5) with the rest-api-key-url-query option both enabled and disabled, as well as with token authentication. Everything appears to be working as expected. However, when upgrading across multiple versions, there can be some changes that might cause issues for older API users. In such cases, recreating the user sometimes resolves the problem.

Regarding the issue @robindbe  mentioned, we have just released Ansible FOS 2.3.9. Are you using the latest version? If so, could you please provide more information, such as your device type, firmware version, and the Ansible error message you received?

```
oot@liang:~/ansible/fgt/github#359# ansible-playbook -i hosts github359.yaml 

PLAY [fortigates] **************************************************************************************

TASK [Fetch simple setting to test API access] *********************************************************
ok: [fortigate01]

TASK [Print reg_forti_system] **************************************************************************
ok: [fortigate01] => {
    "reg_forti_system": {
        "changed": false,
        "failed": false,
        "meta": {
            "action": "",
            "build": 2702,
            "http_method": "GET",
            "http_status": 200,
            "name": "global",
            "path": "system",
            "results": {
                "admin-concurrent": "enable",
                "admin-console-timeout": 0,
                "admin-forticloud-sso-default-profile": "",
                 ..................
                "wimax-4g-usb": "disable",
                "wireless-controller": "enable",
                "wireless-controller-port": 5246
            },
            "revision": "b2c111d4acea735feacf591b37ba6846",
            "serial": "FGT60FTK19009015",
            "status": "success",
            "vdom": "root",
            "version": "v7.4.5"
        }
    }
}

PLAY RECAP *********************************************************************************************
fortigate01                : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

Thanks,
Maxx

**Comment by PhilooLinux** [comment]
Hi @MaxxLiu22, 
I am glad to report that the problem is now resolved for me with the version 2.3.9, I can no longer reproduce since I have upgraded from FOS 2.3.8 to FOS 2.3.9

Thank a lot for your time and efforts.
Philoo

**Comment by robindbe** [comment]
> Hi @robindbe @PhilooLinux ,
> 
> I tested @robindbe's scripts on my FGT 60F (version 7.4.5) with the rest-api-key-url-query option both enabled and disabled, as well as with token authentication. Everything appears to be working as expected. However, when upgrading across multiple versions, there can be some changes that might cause issues for older API users. In such cases, recreating the user sometimes resolves the problem.
> 
> Regarding the issue @robindbe mentioned, we have just released Ansible FOS 2.3.9. Are you using the latest version? If so, could you please provide more information, such as your device type, firmware version, and the Ansible error message you received?
> 
> ```
> oot@liang:~/ansible/fgt/github#359# ansible-playbook -i hosts github359.yaml 
> 
> PLAY [fortigates] **************************************************************************************
> 
> TASK [Fetch simple setting to test API access] *********************************************************
> ok: [fortigate01]
> 
> TASK [Print reg_forti_system] **************************************************************************
> ok: [fortigate01] => {
>     "reg_forti_system": {
>         "changed": false,
>         "failed": false,
>         "meta": {
>             "action": "",
>             "build": 2702,
>             "http_method": "GET",
>             "http_status": 200,
>             "name": "global",
>             "path": "system",
>             "results": {
>                 "admin-concurrent": "enable",
>                 "admin-console-timeout": 0,
>                 "admin-forticloud-sso-default-profile": "",
>                  ..................
>                 "wimax-4g-usb": "disable",
>                 "wireless-controller": "enable",
>                 "wireless-controller-port": 5246
>             },
>             "revision": "b2c111d4acea735feacf591b37ba6846",
>             "serial": "FGT60FTK19009015",
>             "status": "success",
>             "vdom": "root",
>             "version": "v7.4.5"
>         }
>     }
> }
> 
> PLAY RECAP *********************************************************************************************
> fortigate01                : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
> ```
> 
> Thanks, Maxx

Hey @MaxxLiu22 , I upgraded to 2.3.9 and that didn't solve it (which I kinda expected since manual curl calls didn't work either) but recreating the API user did solve the issue for us, so thanks for that suggestion!

**Comment by homero88so** [comment]
youuuu are a life saver community!! I had the same issue for fortigate 7.4.x it was resolved by enabling rest-api-key-url-query  @MaxxLiu22 kudos for u!
